name: Build LaTeX document
on: [push]
jobs:
  build_whitepaper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: sources/whitepaper.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: whitepaper
          path: whitepaper.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: whitepaper
