name: Build and update LaTeX whitepaper
on: [push]

jobs:
  build_whitepaper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX whitepaper
        uses: dante-ev/latex-action@master
        with:
          root_file: sources/ithil-whitepaper.tex

      - name: Configure git information
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

      - name: Prepare and commit the new PDF file
        run: |
          git add ithil-whitepaper.pdf
          git commit -am "Updated the whitepaper"
          git push
